### ISSUE TITLE
Gestione JWT scaduti

### ISSUE THREAD

**Issue by riccardocannella** [ecommerce-unicam/Sito-Tranquillo#125]
Ho notato che se un token scade, viene comunque messa la navbar "siautenticazione" perché non fa il controllo sulla scadenza.

**Comment by riccardocannella** [comment]
In altre parti del sito ovviamente poi la verifica del JWT non va perché è scaduto

**Comment by michele-biondi-unicam** [comment]
Sisi ne stavo parlando ieri con Andrea, sto valutando come farlo,
sicuramente va aumentata la durata del token che 24 minuti so pochi, poi
penso di fare un middleware per il controllo, mi resta solo da capire come
farlo il più semplice possibile per la parte frontend

Il 24 ott 2017 11:58 AM, "Riccardo Cannella" <notifications@github.com> ha
scritto:

**Comment by michele-biondi-unicam** [comment]
Per adesso, se ti serve per provare qualcosa basta che sloggi e riloggi e
te ne ridá un'altro aggiornato

Il 24 ott 2017 12:00 PM, "MICHELE BIONDI" <michele.biondi@studenti.unicam.it>
ha scritto:

**Comment by michele-biondi-unicam** [comment]
FUXATO
