### ISSUE TITLE
La registrazione nel backend permette di registrare due utenti con lo stesso nome

### ISSUE THREAD

**Issue by michele-biondi-unicam** [ecommerce-unicam/Sito-Tranquillo#20]
E' semplicemente un promemoria, ci penso io.

**Comment by riccardocannella** [comment]
questa issue si può chiudere credo

**Comment by michele-biondi-unicam** [comment]
Si chiudono da sole appena si fa il merge della pull request relativa

Il 14 set 2017 5:28 PM, "Riccardo Cannella" <notifications@github.com> ha
scritto:
