### ISSUE TITLE
bcrypt dà errori nell'installazione sotto Windows

### ISSUE THREAD

**Issue by riccardocannella** [ecommerce-unicam/Sito-Tranquillo#25]
Ho trovato due soluzioni qui: https://stackoverflow.com/questions/29320201/error-installing-bcrypt-with-npm , provo prima con i tool suggeriti più in basso, se ancora non dovesse andare cambio la dipendenza da bcrypt a bcryptjs

**Comment by michele-biondi-unicam** [comment]
A questo punto direi di cambiare direttamente a bcryptjs, l'API c'è scritto che è uguale, quindi anche dal mio punto di vista non cambia nulla.
