### ISSUE TITLE
La registrazione permette due utenti con la stessa email

### ISSUE THREAD

**Issue by michele-biondi-unicam** [ecommerce-unicam/Sito-Tranquillo#26]
Lo correggo insieme all'issue #20

**Comment by petrellicorrado** [comment]
https://code.tutsplus.com/tutorials/authenticating-nodejs-applications-with-passport--cms-21619
se può esserti utile

**Comment by riccardocannella** [comment]
questa issue si può chiudere credo, come l'altra
