### ISSUE TITLE
Errore pulling 

### ISSUE THREAD

**Issue by petrellicorrado** [ecommerce-unicam/Sito-Tranquillo#73]
Per sbaglio ho lavorato in upstream ed ho pullato 2 commit...
f963c1f99a889a9d523e42e2ac5a1356896f4cbd
2867a2b6a553085f428b7e566ffda2428e66a66e

Controllate e ditemi se vi vanno bene

**Comment by michele-biondi-unicam** [comment]
Domani mattina controllo, male che va si fa un revert a 2 commit prima

Il 26 set 2017 11:40 PM, "petrellicorrado" <notifications@github.com> ha
scritto:

**Comment by michele-biondi-unicam** [comment]
Va tutto bene continuiamo a lavorarci io e Andrea per la registrazione
